#!/usr/bin/env bash

echo "Generating 1password-direnv-tool.rb cask file..."

TARGET_DIR="${1}"
shift || true

if [[ ! -d "${TARGET_DIR}" ]]; then
  echo "Error: TARGET_DIR '${TARGET_DIR}' does not exist or is not a directory." >&2
  exit 1
fi

TARGET_FILENAME="1password-direnv-tool.rb"
TARGET_FULLPATH="${TARGET_DIR}/${TARGET_FILENAME}"

if [[ ! -z "${GITHUB_OUTPUT}" ]]; then
  (
    echo "target_name=1password-direnv-tool"; 
    echo "target_path=${TARGET_FULLPATH}";
    echo "target_filename=${TARGET_FILENAME}";
  ) >> "${GITHUB_OUTPUT}"
fi

VERSION="${VERSION:-${GITHUB_REF##*/}}"

SHA_DARWIN_ARM64="$(sha256sum artifacts/archives/1password-direnv-tool_darwin_arm64.tar.gz | awk '{print $1}')"

tee "${TARGET_FULLPATH}" << EOF
# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "1password-direnv-tool" do
  name "1password-direnv-tool"
  desc "1Password Direnv Tool is a command-line utility that integrates 1Password with direnv, allowing you to securely manage environment variables on a per-directory basis using 1Password items."
  homepage "https://github.com/na4ma4/1password-direnv-tool"
  version "${VERSION}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "1password-direnv-tool"

  on_macos do
    on_arm do
      url "https://github.com/na4ma4/1password-direnv-tool/releases/download/v#{version}/1password-direnv-tool_darwin_arm64.tar.gz"
      sha256 "${SHA_DARWIN_ARM64}"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/1password-direnv-tool"]
    end
  end

  # No zap stanza required
end
EOF

echo "Generated 1password-direnv-tool.rb"
